function webclient(){var bb='',$=' top: -1000px;',yb='" for "gwt:onLoadErrorFn"',wb='" for "gwt:onPropertyErrorFn"',hb='");',zb='#',hc='.cache.js',Bb='/',Hb='//',$b='1BE1046EC53B7AE832E1BDBEFBC1B1D2',_b='76FB30F8C073BF54F701EEBB8DF12653',gc=':',fc=':1',qb='::',oc=':moduleBase',ab='<!doctype html>',cb='<html><head><\/head><body><\/body><\/html>',tb='=',Ab='?',vb='Bad handler "',ac='C7D8587A583EF91650E7D882C9EDD25B',bc='CDA90E210514CCEE8A79ABCFE0FE2F4D',cc='CF5C306E1BF7A4D2622CD7603D14A29E',_='CSS1Compat',fb='Chrome',dc='DD1E5D54FDE73E16E216F8A3D134C581',eb='DOMContentLoaded',V='DUMMY',ec='F78A1E8C4827A8888C749A666A869F81',nc='Ignoring non-whitelisted Dev Mode URL: ',mc='__gwtDevModeHook:webclient',Gb='base',Eb='baseUrl',Q='begin',W='body',P='bootstrap',Db='clear.cache.gif',sb='content',jc='end',gb='eval("',lc='file:',Vb='gecko',Wb='gecko1_8',R='gwt.codesvr.webclient=',S='gwt.codesvr=',xb='gwt:onLoadErrorFn',ub='gwt:onPropertyErrorFn',rb='gwt:property',mb='head',kc='http:',Rb='ie10',Ub='ie6',Tb='ie8',Sb='ie9',X='iframe',Cb='img',jb='javascript',Y='javascript:""',ic='loadExternalRefs',nb='meta',Kb='mobile',Ib='mobile.user.agent',Lb='mobilesafari',lb='moduleRequested',kb='moduleStartup',Qb='msie',ob='name',Mb='none',Ob='opera',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',Pb='safari',ib='script',Yb='selectingPermutation',U='startup',db='undefined',Xb='unknown',Nb='user.agent',T='webclient',Zb='webclient.devmode.js',Fb='webclient.nocache.js',pb='webclient::',Jb='webkit';var o=window;var p=document;r(P,Q);function q(){var a=o.location.search;return a.indexOf(R)!=-1||a.indexOf(S)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:T,sessionId:o.__gwtStatsSessionId,subSystem:U,evtGroup:a,millis:(new Date).getTime(),type:b})}}
webclient.__sendStats=r;webclient.__moduleName=T;webclient.__errFn=null;webclient.__moduleBase=V;webclient.__softPermutationId=0;webclient.__computePropValue=null;webclient.__getPropMap=null;webclient.__gwtInstallCode=function(){};webclient.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[T]={moduleName:T};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(W)[0]}
function B(){if(v){return}var a=p.createElement(X);a.src=Y;a.id=T;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==_?ab:bb;v.write(b+cb);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(fb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(gb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(hb));g=f.createElement(ib);g.language=jb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(ib);g.language=jb;g.text=c[i];e.appendChild(g);d(e,g)}}}
webclient.onScriptDownloaded=function(a){l(function(){m(a)})};r(kb,lb);var n=p.createElement(ib);n.src=k;p.getElementsByTagName(mb)[0].appendChild(n)}
webclient.__startLoadingFragment=function(a){return G(a)};webclient.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(ib);c.language=jb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(nb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(ob),k;if(j){j=j.replace(pb,bb);if(j.indexOf(qb)>=0){continue}if(j==rb){k=i.getAttribute(sb);if(k){var l,m=k.indexOf(tb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=bb}c[j]=l}}else if(j==ub){k=i.getAttribute(sb);if(k){try{d=eval(k)}catch(a){alert(vb+k+wb)}}}else if(j==xb){k=i.getAttribute(sb);if(k){try{e=eval(k)}catch(a){alert(vb+k+yb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;webclient.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(zb);if(b==-1){b=a.length}var c=a.indexOf(Ab);if(c==-1){c=a.length}var d=a.lastIndexOf(Bb,Math.min(c,b));return d>=0?a.substring(0,d+1):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Cb);b.src=a+Db;a=e(b.src)}return a}
function g(){var a=t(Eb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Fb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Gb);if(a.length>0){return a[a.length-1].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Hb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return webclient.__moduleBase+a}
function H(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Ib]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Jb)>=0&&a.indexOf(Kb)>=0){return Lb}return Mb};i[Ib]={mobilesafari:0,none:1};j[Nb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Ob)!=-1}())return Ob;if(function(){return b.indexOf(Jb)!=-1}())return Pb;if(function(){return b.indexOf(Qb)!=-1&&p.documentMode>=10}())return Rb;if(function(){return b.indexOf(Qb)!=-1&&p.documentMode>=9}())return Sb;if(function(){return b.indexOf(Qb)!=-1&&p.documentMode>=8}())return Tb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Ub;if(function(){return b.indexOf(Vb)!=-1}())return Wb;return Xb};i[Nb]={gecko1_8:0,ie10:1,ie6:2,ie8:3,ie9:4,opera:5,safari:6};s=function(a,b){return b in i[a]};webclient.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};webclient.__computePropValue=k;o.__gwt_activeModules[T].bindings=webclient.__getPropMap;r(P,Yb);if(q()){return G(Zb)}var l;try{h([Mb,Tb],$b);h([Mb,Sb],_b);h([Mb,Rb],ac);h([Mb,Wb],bc);h([Mb,Ob],cc);h([Mb,Ub],dc);h([Lb,Pb],ec);h([Mb,Pb],ec);h([Lb,Pb],ec+fc);h([Mb,Pb],ec+fc);l=f[k(Ib)][k(Nb)];var m=l.indexOf(gc);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}webclient.__softPermutationId=g;return G(l+hc)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(ic,Q);r(ic,jc)}
D();webclient.__moduleBase=F();u[T].moduleBase=webclient.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==kc||o.location.protocol==lc);o.__gwt_activeModules[T].canRedirect=K;if(K){var L=mc;var M=o.sessionStorage[L];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(M)){if(M&&(window.console&&console.log)){console.log(nc+M)}M=bb}if(M&&!o[L]){o[L]=true;o[L+oc]=F();var N=p.createElement(ib);N.src=M;var O=p.getElementsByTagName(mb)[0];O.insertBefore(N,O.firstElementChild||O.children[0]);return false}}}I();r(P,jc);C(J);return true}
webclient.succeeded=webclient();